<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <EmbeddedResource Include="Resources\technical-tokens.txt"
                      LogicalName="LayoutFix.Core.Resources.technical-tokens.txt" />
    <EmbeddedResource Include="Resources\frequent-source-tokens.txt"
                      LogicalName="LayoutFix.Core.Resources.frequent-source-tokens.txt" />
  </ItemGroup>

</Project>
