<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
    <SelfContained>true</SelfContained>
    <RuntimeIdentifier>win-x64</RuntimeIdentifier>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\LayoutFix.Core\LayoutFix.Core.csproj" />
    <ProjectReference Include="..\..\src\LayoutFix.Infrastructure\LayoutFix.Infrastructure.csproj" />
    <ProjectReference Include="..\..\src\LayoutFix\LayoutFix.csproj" />
  </ItemGroup>
</Project>
